import Head from "next/head";
import dynamic from "next/dynamic";
import { useState } from "react";
const AceEditor = dynamic(() => import("@/components/AceEditor"), {
  ssr: false,
});
const SyntaxHighlighter = dynamic(
  () => import("@/components/SyntaxHighlighter"),
  {
    ssr: false,
  }
);

export default function Home() {
  const [value, setValue] = useState<string>("");
  const [tsValue, setTsValue] = useState<string>("");
  const postJsonData = async () => {
    const response = await fetch("/api/jsontots", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ jsonData: value }),
    });
    const data = await response.json();
    setTsValue(data.result);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{ display: "grid", placeItems: "center", minHeight: "100vvh" }}
      >
        <h1>JSON TO TypeScript Type</h1>
        <div style={{ marginTop: 40 }}>
          <AceEditor setValue={setValue} />
        </div>
        <button style={{ marginTop: 10 }} onClick={() => postJsonData()}>
          Convert
        </button>

        <div style={{ marginTop: 20 }}>
          <SyntaxHighlighter code={tsValue} />
        </div>
      </main>
    </>
  );
}
