import Head from "next/head";
import styles from "@/styles/Home.module.css";
import dynamic from "next/dynamic";
import { useState } from "react";
const AceEditor = dynamic(() => import("@/components/AceEditor"), {
  ssr: false,
});
const SyntaxHighlighter = dynamic(
  () => import("@/components/SyntaxHighlighter"),
  {
    ssr: false,
  }
);

export default function Home() {
  const [value, setValue] = useState<string>("");
  const [tsValue, setTsValue] = useState<string>("");
  const postJsonData = async () => {
    const response = await fetch("/api/jsontots", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ jsonData: value }),
    });
    const data = await response.json();
    setTsValue(data.result);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AceEditor setValue={setValue} />
        <button onClick={() => postJsonData()}>Convert</button>

        <div>
          <SyntaxHighlighter code={tsValue} />
        </div>
      </main>
    </>
  );
}
